controller_manager:
  ros__parameters:
    update_rate: 30
    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    storage_servo:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - storage_joint
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.362
    wheel_radius: 0.0485
    use_stamped_vel: false

storage_servo:
  ros__parameters:
    joints:
      - storage_joint
    command_interfaces:
      - velocity
    state_interfaces: 
      - position
      - velocity
    has_velocity_limits: true
    max_velocity: 1.0

fts_broadcaster:
  ros__parameters:
    interface_names.force.x: system_interface/force.x
    interface_names.torque.z: system_interface/torque.z
    frame_id: base_link