twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 10
      man_nav:
        topic   : cmd_vel_mn
        timeout : 0.5
        priority: 20
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 30
      keyboard:
        topic   : cmd_vel_key
        timeout : 0.5
        priority: 50
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100