twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      keyboard:
        topic   : cmd_vel_key
        timeout : 0.5
        priority: 100